### ISSUE TITLE
wp_register_style called incorrectly

### ISSUE THREAD

**Issue by EdHurtig** [wolfd/MBTAShortcoder#4]
Lines 24-30 of the Shortcoder class need to be moved to a function that runs on wp_enqueue_scripts

Error from Wordpress debug.log
PHP Notice:  wp_register_style was called <strong>incorrectly</strong>. Scripts and styles should not be registered or enqueued until the <code>wp_enqueue_scripts</code>, <code>admin_enqueue_scripts</code>, or <code>login_enqueue_scripts</code> hooks. Please see <a href="http://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 3.3.) in /var/dds-server/wp-includes/functions.php on line 3245

**Comment by wolfd** [comment]
Fixed as of https://github.com/wolfd/MBTAShortcoder/commit/1dd24b1c243d5f79ba9ce11c1c0f1c1e4463efa2
